In [1]:
# Import dependencies
import pandas as pd

In [2]:
# Import homicide data
murders_df = pd.read_csv("Resources/murders_raw.csv", low_memory=False)
murders_df.head()

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
0,1,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,January,1,Murder or Manslaughter,...,Unknown,Male,15,Native American/Alaska Native,Unknown,Acquaintance,Blunt Object,0,0,FBI
1,2,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,March,1,Murder or Manslaughter,...,Unknown,Male,42,White,Unknown,Acquaintance,Strangulation,0,0,FBI
2,3,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,March,2,Murder or Manslaughter,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Unknown,0,0,FBI
3,4,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,April,1,Murder or Manslaughter,...,Unknown,Male,42,White,Unknown,Acquaintance,Strangulation,0,0,FBI
4,5,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,April,2,Murder or Manslaughter,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Unknown,0,1,FBI

In [3]:
# Filter to California homicides
murders_df = murders_df[murders_df["State"]=="California"]
murders_df.head()

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
1067,1068,CA00100,Alameda,Sheriff,Alameda,California,1980,April,1,Murder or Manslaughter,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Knife,0,1,FBI
1068,1069,CA00100,Alameda,Sheriff,Alameda,California,1980,August,1,Murder or Manslaughter,...,Not Hispanic,Male,39,White,Not Hispanic,Son,Handgun,0,0,FBI
1069,1070,CA00100,Alameda,Sheriff,Alameda,California,1980,October,1,Murder or Manslaughter,...,Not Hispanic,Unknown,0,Unknown,Unknown,Unknown,Fire,0,1,FBI
1070,1071,CA00100,Alameda,Sheriff,Alameda,California,1980,November,1,Murder or Manslaughter,...,Hispanic,Unknown,0,Unknown,Unknown,Unknown,Knife,0,0,FBI
1071,1072,CA00100,Alameda,Sheriff,Alameda,California,1980,November,2,Murder or Manslaughter,...,Not Hispanic,Unknown,0,Unknown,Unknown,Unknown,Knife,0,0,FBI

In [4]:
# Rename City column County
murders_df.rename(columns={"City":"County"}, inplace=True)
murders_df.head()

,Record ID,Agency Code,Agency Name,Agency Type,County,State,Year,Month,Incident,Crime Type,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
1067,1068,CA00100,Alameda,Sheriff,Alameda,California,1980,April,1,Murder or Manslaughter,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Knife,0,1,FBI
1068,1069,CA00100,Alameda,Sheriff,Alameda,California,1980,August,1,Murder or Manslaughter,...,Not Hispanic,Male,39,White,Not Hispanic,Son,Handgun,0,0,FBI
1069,1070,CA00100,Alameda,Sheriff,Alameda,California,1980,October,1,Murder or Manslaughter,...,Not Hispanic,Unknown,0,Unknown,Unknown,Unknown,Fire,0,1,FBI
1070,1071,CA00100,Alameda,Sheriff,Alameda,California,1980,November,1,Murder or Manslaughter,...,Hispanic,Unknown,0,Unknown,Unknown,Unknown,Knife,0,0,FBI
1071,1072,CA00100,Alameda,Sheriff,Alameda,California,1980,November,2,Murder or Manslaughter,...,Not Hispanic,Unknown,0,Unknown,Unknown,Unknown,Knife,0,0,FBI

In [5]:
# Drop irrelevant columns
murders_df = murders_df.drop(columns=['Agency Code', 'Record Source'])
murders_df.head()

,Record ID,Agency Name,Agency Type,County,State,Year,Month,Incident,Crime Type,Crime Solved,...,Victim Race,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count
1067,1068,Alameda,Sheriff,Alameda,California,1980,April,1,Murder or Manslaughter,No,...,White,Unknown,Unknown,0,Unknown,Unknown,Unknown,Knife,0,1
1068,1069,Alameda,Sheriff,Alameda,California,1980,August,1,Murder or Manslaughter,Yes,...,White,Not Hispanic,Male,39,White,Not Hispanic,Son,Handgun,0,0
1069,1070,Alameda,Sheriff,Alameda,California,1980,October,1,Murder or Manslaughter,No,...,Black,Not Hispanic,Unknown,0,Unknown,Unknown,Unknown,Fire,0,1
1070,1071,Alameda,Sheriff,Alameda,California,1980,November,1,Murder or Manslaughter,No,...,White,Hispanic,Unknown,0,Unknown,Unknown,Unknown,Knife,0,0
1071,1072,Alameda,Sheriff,Alameda,California,1980,November,2,Murder or Manslaughter,No,...,White,Not Hispanic,Unknown,0,Unknown,Unknown,Unknown,Knife,0,0

In [6]:
# Rename columns to remove spaces
murders_df.rename(columns={"Record ID": "RecordId",
                  "Agency Name":"AgencyName",
                  "Agency Type": "AgencyType",
                  "Crime Type": "CrimeType",
                  "Crime Solved": "CrimeSolved",
                  "Victim Sex": "VictimSex",
                  "Victim Age": "VictimAge",
                  "Victim Race": "VictimRace",
                  "Victim Ethnicity": "VictimEthnicity",
                  "Victim Count": "VictimCount",
                  "Perpetrator Sex": "PerpetratorSex",
                  "Perpetrator Age": "PerpetratorAge",
                  "Perpetrator Race": "PerpetratorRace",
                  "Perpetrator Ethnicity": "PerpetratorEthnicity",         
                  "Perpetrator Count": "PerpetratorCount"},
                  inplace=True)
murders_df.head()

,RecordId,AgencyName,AgencyType,County,State,Year,Month,Incident,CrimeType,CrimeSolved,...,VictimRace,VictimEthnicity,PerpetratorSex,PerpetratorAge,PerpetratorRace,PerpetratorEthnicity,Relationship,Weapon,VictimCount,PerpetratorCount
1067,1068,Alameda,Sheriff,Alameda,California,1980,April,1,Murder or Manslaughter,No,...,White,Unknown,Unknown,0,Unknown,Unknown,Unknown,Knife,0,1
1068,1069,Alameda,Sheriff,Alameda,California,1980,August,1,Murder or Manslaughter,Yes,...,White,Not Hispanic,Male,39,White,Not Hispanic,Son,Handgun,0,0
1069,1070,Alameda,Sheriff,Alameda,California,1980,October,1,Murder or Manslaughter,No,...,Black,Not Hispanic,Unknown,0,Unknown,Unknown,Unknown,Fire,0,1
1070,1071,Alameda,Sheriff,Alameda,California,1980,November,1,Murder or Manslaughter,No,...,White,Hispanic,Unknown,0,Unknown,Unknown,Unknown,Knife,0,0
1071,1072,Alameda,Sheriff,Alameda,California,1980,November,2,Murder or Manslaughter,No,...,White,Not Hispanic,Unknown,0,Unknown,Unknown,Unknown,Knife,0,0

In [7]:
# Examine shape of dataset
murders_df.shape

(99783, 22)

In [8]:
# Check for null values
murders_df.isnull().sum()

RecordId                0
AgencyName              0
AgencyType              0
County                  0
State                   0
Year                    0
Month                   0
Incident                0
CrimeType               0
CrimeSolved             0
VictimSex               0
VictimAge               0
VictimRace              0
VictimEthnicity         0
PerpetratorSex          0
PerpetratorAge          0
PerpetratorRace         0
PerpetratorEthnicity    0
Relationship            0
Weapon                  0
VictimCount             0
PerpetratorCount        0
dtype: int64

In [9]:
# Check datatypes
murders_df.dtypes

RecordId                 int64
AgencyName              object
AgencyType              object
County                  object
State                   object
Year                     int64
Month                   object
Incident                 int64
CrimeType               object
CrimeSolved             object
VictimSex               object
VictimAge                int64
VictimRace              object
VictimEthnicity         object
PerpetratorSex          object
PerpetratorAge          object
PerpetratorRace         object
PerpetratorEthnicity    object
Relationship            object
Weapon                  object
VictimCount              int64
PerpetratorCount         int64
dtype: object

In [10]:
# Import county demographics data
county_df = pd.read_csv("Resources/county_raw.csv")
county_df.head()

,CensusId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
0,1001,Alabama,Autauga,55221,26745,28476,2.6,75.8,18.5,0.4,...,0.5,1.3,1.8,26.5,23986,73.6,20.9,5.5,0.0,7.6
1,1003,Alabama,Baldwin,195121,95314,99807,4.5,83.1,9.5,0.6,...,1.0,1.4,3.9,26.4,85953,81.5,12.3,5.8,0.4,7.5
2,1005,Alabama,Barbour,26932,14497,12435,4.6,46.2,46.7,0.2,...,1.8,1.5,1.6,24.1,8597,71.8,20.8,7.3,0.1,17.6
3,1007,Alabama,Bibb,22604,12073,10531,2.2,74.5,21.4,0.4,...,0.6,1.5,0.7,28.8,8294,76.8,16.1,6.7,0.4,8.3
4,1009,Alabama,Blount,57710,28512,29198,8.6,87.9,1.5,0.3,...,0.9,0.4,2.3,34.9,22189,82.0,13.5,4.2,0.4,7.7

In [11]:
# Filter to California demographics
county_df = county_df[county_df["State"]=="California"]
county_df.head()

,CensusId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
186,6001,California,Alameda,1584983,776699,808284,22.6,33.0,11.3,0.3,...,3.7,3.5,5.6,30.7,778132,78.7,13.8,7.4,0.1,8.3
187,6003,California,Alpine,1131,654,477,9.5,64.1,1.0,19.4,...,8.4,1.8,13.7,24.3,408,57.4,32.8,9.8,0.0,10.7
188,6005,California,Amador,36995,20012,16983,12.9,79.7,2.2,1.8,...,3.6,0.9,5.6,29.3,12573,64.5,23.4,11.8,0.3,14.0
189,6007,California,Butte,222564,110115,112449,15.2,73.8,1.4,0.7,...,3.7,3.9,5.8,19.9,89411,71.8,17.3,10.5,0.5,12.1
190,6009,California,Calaveras,44767,22143,22624,11.1,82.5,0.6,0.9,...,1.9,0.8,7.5,33.6,16248,65.2,20.3,13.9,0.6,12.1

In [12]:
# Drop irrelevant columns
county_df = county_df.drop(columns=['Professional', 'Service', 'Office', 'Construction', 
                                    'Production', 'Drive', 'Carpool', 'Transit', 'Walk', 'OtherTransp',
                                   'WorkAtHome', 'MeanCommute', 'PrivateWork', 'PublicWork', 'SelfEmployed', 'FamilyWork'])
county_df.head()

,CensusId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,...,Pacific,Citizen,Income,IncomeErr,IncomePerCap,IncomePerCapErr,Poverty,ChildPoverty,Employed,Unemployment
186,6001,California,Alameda,1584983,776699,808284,22.6,33.0,11.3,0.3,...,0.8,1025865,75619.0,613.0,37285,279,12.5,15.2,778132,8.3
187,6003,California,Alpine,1131,654,477,9.5,64.1,1.0,19.4,...,1.4,865,52917.0,13603.0,21415,3057,17.5,8.5,408,10.7
188,6005,California,Amador,36995,20012,16983,12.9,79.7,2.2,1.8,...,0.1,30376,54171.0,4208.0,27473,2016,12.8,22.5,12573,14.0
189,6007,California,Butte,222564,110115,112449,15.2,73.8,1.4,0.7,...,0.2,169724,43444.0,1068.0,24259,637,21.9,23.9,89411,12.1
190,6009,California,Calaveras,44767,22143,22624,11.1,82.5,0.6,0.9,...,0.3,35415,53233.0,3774.0,29553,1398,12.6,13.3,16248,12.1

In [13]:
# Examine shape of dataset
county_df.shape

(58, 21)

In [14]:
# Check for null values
county_df.isnull().sum()

CensusId           0
State              0
County             0
TotalPop           0
Men                0
Women              0
Hispanic           0
White              0
Black              0
Native             0
Asian              0
Pacific            0
Citizen            0
Income             0
IncomeErr          0
IncomePerCap       0
IncomePerCapErr    0
Poverty            0
ChildPoverty       0
Employed           0
Unemployment       0
dtype: int64

In [15]:
# Check datatypes
county_df.dtypes

CensusId             int64
State               object
County              object
TotalPop             int64
Men                  int64
Women                int64
Hispanic           float64
White              float64
Black              float64
Native             float64
Asian              float64
Pacific            float64
Citizen              int64
Income             float64
IncomeErr          float64
IncomePerCap         int64
IncomePerCapErr      int64
Poverty            float64
ChildPoverty       float64
Employed             int64
Unemployment       float64
dtype: object

In [16]:
# Export cleaned datasets to CSV
murders_df.to_csv(r'Resources/murders_clean.csv', index=False)
county_df.to_csv(r'Resources/county_clean.csv', index=False)